/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaMovie */

#ifndef _Included_javaMovie
#define _Included_javaMovie
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaMovie
 * Method:    initMovie
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javaMovie_initMovie
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
