#/bin/sh
# Concatenate all js files into jglTask.js. Ensure you are in the directory "jgl/lib/task". 
# This places jgl library into one file. Easier to include one file into HTML than many.
# WARNING: jglTask.js is moved one level up into directory jgl/lib. DON'T modify jglTask.js. 
# Instead, individual js files in the "task" folder need to be modified and 
# jglTask.js needs to be regenerated by running this script again  

find *.js -not -name "jglTask.js" -exec cat {} \; > jglTask.js
mv jglTask.js ../
